### PR TITLE
Migrated to null safety

### PR DESCRIPTION
**Pull request by uttufy**

### CODE REVIEW

**Comment by Aulig** [comment]
Would be awesome if you could merge and publish this on pub.dev @tejainece :)
Thanks so much!

**Comment by albemala** [comment]
I'm using this in production and it works fine. Any chance to have this merged and released please? :)

**Comment by tejainece** [comment]
I will do it tonight.

**Comment by albemala** [comment]
Thank you! 🙏

**Review by tejainece — APPROVED** [review]
LGTM

**Comment by tejainece** [comment]
Pubished to pub.dev as version 2.0.0

**Pull request merged**
